# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIhFgaSPx7FNNqW4SRd7JeTgvxwKkSWo
"""

# app.py


import streamlit as st
import joblib
from preprocess import preprocess

model = joblib.load("app1/model.pkl")
vectorizer = joblib.load("app1/vectorizer.pkl")

st.title("📰 Fake News Detection")
tweet = st.text_area("Enter a tweet")

if st.button("Predict"):
    cleaned = preprocess(tweet)
    vect = vectorizer.transform([cleaned])
    pred = model.predict(vect)[0]

    if pred == 1:
        st.success("✅ Real Tweet")
    else:
        st.error("❌ Fake or Unrelated Tweet")